server:
  port: 8000

spring:
  application:
    name: consumer-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    #开启熔断
    enabled: true

hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


