server:
  port: 10000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证中心
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/oauth/**
          filters:
            - StripPrefix=1
        # 用户中心
        - id: user
        uri: lb://user
        predicates:
          - Path=/user/users/**
          - Path=/user/permissions/**
          - Path=/user/roles/**
          - Path=/user/users-anon/**
        filters:
          - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
